# These are supported funding model platforms

github: upendra-manike
# patreon: # Replace with up to 4 Patreon usernames
# open_collective: # Replace with up to 4 Open Collective usernames
# ko_fi: # Replace with up to 4 Ko-fi usernames
# tidelift: # Replace with up to 4 Tidelift platform/package-name e.g., npm/babel
# community_bridge: # Replace with up to 4 Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with up to 4 Liberapay usernames
# issuehunt: # Replace with up to 4 IssueHunt usernames
# otechie: # Replace with up to 4 Otechie usernames
# lfx_crowdfunding: # Replace with up to 4 LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with up to 4 Polar project names
# buy_me_a_coffee: # Replace with up to 4 Buy Me a Coffee usernames
# thanks_dev: # Replace with up to 4 thanks.dev project names
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

